(function(){
  'use strict';
  const cfg=window.DG_CLOUD_CONFIG||{};
  if(!cfg.appId||!Array.isArray(cfg.keys)){console.warn('DG Cloud Sync: konfiguracija manjka.');return;}
  const deviceId=localStorage.getItem('dgCloudDeviceId')||(('dev-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,8)));
  localStorage.setItem('dgCloudDeviceId',deviceId);
  const metaKey='dgCloudMeta:'+cfg.appId;
  const original={setItem:localStorage.setItem.bind(localStorage),removeItem:localStorage.removeItem.bind(localStorage),clear:localStorage.clear.bind(localStorage)};
  let applying=false, uploadTimer=null, unsubscribe=null, currentUser=null;
  const tracked=k=>cfg.keys.includes(k)||(cfg.prefixes||[]).some(p=>k.startsWith(p));
  const collect=()=>{const values={};for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i);if(tracked(k))values[k]=localStorage.getItem(k);}return values};
  const hasLocal=()=>Object.keys(collect()).length>0;
  function markLocalChange(){if(applying||!currentUser)return;clearTimeout(uploadTimer);uploadTimer=setTimeout(upload,800)}
  localStorage.setItem=function(k,v){original.setItem(k,v);if(tracked(k))markLocalChange()};
  localStorage.removeItem=function(k){original.removeItem(k);if(tracked(k))markLocalChange()};
  localStorage.clear=function(){original.clear();markLocalChange()};

  function toast(msg,isError){let e=document.getElementById('dg-cloud-toast');if(!e){e=document.createElement('div');e.id='dg-cloud-toast';e.style.cssText='position:fixed;left:50%;bottom:86px;transform:translateX(-50%);z-index:2147483647;background:#111;color:#fff;padding:10px 14px;border-radius:12px;font:600 13px system-ui;box-shadow:0 8px 24px #0004;max-width:85vw;text-align:center;opacity:0;transition:.2s';document.body.appendChild(e)}e.textContent=msg;e.style.background=isError?'#a61b1b':'#111';e.style.opacity='1';clearTimeout(e._t);e._t=setTimeout(()=>e.style.opacity='0',2400)}
  function injectUI(){
    if(document.getElementById('dg-cloud-button'))return;
    const b=document.createElement('button');b.id='dg-cloud-button';b.type='button';b.title='DG Cloud Sync';b.textContent='☁️';b.style.cssText='position:fixed;right:14px;top:14px;z-index:2147483646;width:44px;height:44px;border:0;border-radius:50%;background:#fff;color:#111;font-size:21px;box-shadow:0 4px 18px #0003;cursor:pointer';b.onclick=openPanel;document.body.appendChild(b);
    const p=document.createElement('div');p.id='dg-cloud-panel';p.style.cssText='display:none;position:fixed;inset:0;z-index:2147483645;background:#0008;padding:18px;align-items:center;justify-content:center;font-family:system-ui';p.innerHTML=`<div style="width:min(430px,100%);max-height:86vh;overflow:auto;background:#fff;color:#111;border-radius:20px;padding:20px;box-shadow:0 20px 60px #0006"><div style="display:flex;justify-content:space-between;gap:12px;align-items:center"><div><div style="font-size:21px;font-weight:800">DG Cloud Sync</div><div id="dg-cloud-status" style="font-size:13px;color:#666;margin-top:3px">Preverjanje …</div></div><button id="dg-cloud-close" style="border:0;background:#eee;border-radius:50%;width:36px;height:36px;font-size:20px">×</button></div><div id="dg-cloud-user" style="margin:16px 0;padding:12px;background:#f4f6f8;border-radius:12px;font-size:14px"></div><div style="display:grid;gap:10px"><button id="dg-cloud-login" style="padding:12px;border:0;border-radius:12px;background:#1769e0;color:#fff;font-weight:700">Prijava z Googlom</button><button id="dg-cloud-syncnow" style="padding:12px;border:0;border-radius:12px;background:#e9f0ff;color:#1453aa;font-weight:700">Sinhroniziraj zdaj</button><button id="dg-cloud-export" style="padding:12px;border:0;border-radius:12px;background:#eee;font-weight:700">Izvozi varnostno kopijo</button><label style="padding:12px;border-radius:12px;background:#eee;font-weight:700;text-align:center;cursor:pointer">Uvozi varnostno kopijo<input id="dg-cloud-import" type="file" accept="application/json" hidden></label><button id="dg-cloud-logout" style="padding:12px;border:0;border-radius:12px;background:#ffe9e9;color:#9b1c1c;font-weight:700">Odjava</button></div><p style="font-size:12px;color:#666;line-height:1.45;margin:15px 2px 0">Ob prvi prijavi se obstoječi podatki iz te naprave varno prenesejo v oblak. Nato se spremembe sinhronizirajo med prijavljenimi napravami.</p></div>`;document.body.appendChild(p);
    p.onclick=e=>{if(e.target===p)closePanel()};document.getElementById('dg-cloud-close').onclick=closePanel;document.getElementById('dg-cloud-login').onclick=login;document.getElementById('dg-cloud-logout').onclick=()=>firebase.auth().signOut();document.getElementById('dg-cloud-syncnow').onclick=upload;document.getElementById('dg-cloud-export').onclick=exportBackup;document.getElementById('dg-cloud-import').onchange=importBackup;updateUI();
  }
  function openPanel(){document.getElementById('dg-cloud-panel').style.display='flex';updateUI()}
  function closePanel(){document.getElementById('dg-cloud-panel').style.display='none'}
  function updateUI(){const s=document.getElementById('dg-cloud-status'),u=document.getElementById('dg-cloud-user'),li=document.getElementById('dg-cloud-login'),lo=document.getElementById('dg-cloud-logout'),sy=document.getElementById('dg-cloud-syncnow');if(!s)return;if(currentUser){s.textContent=navigator.onLine?'Povezano in pripravljeno':'Brez povezave – spremembe se bodo poslale pozneje';u.textContent=currentUser.displayName||currentUser.email||'Prijavljen uporabnik';li.style.display='none';lo.style.display='block';sy.style.display='block'}else{s.textContent='Sinhronizacija ni vključena';u.textContent='Za uporabo na več napravah se prijavi z istim Google računom.';li.style.display='block';lo.style.display='none';sy.style.display='none'}}
  async function login(){try{const provider=new firebase.auth.GoogleAuthProvider();await firebase.auth().signInWithPopup(provider)}catch(e){if(['auth/popup-blocked','auth/cancelled-popup-request','auth/operation-not-supported-in-this-environment'].includes(e.code)){await firebase.auth().signInWithRedirect(new firebase.auth.GoogleAuthProvider())}else{console.error(e);toast('Prijava ni uspela: '+(e.message||e.code),true)}}}
  function ref(){return firebase.firestore().collection('users').doc(currentUser.uid).collection('apps').doc(cfg.appId)}
  async function upload(){if(!currentUser)return;try{const payload={appId:cfg.appId,appName:cfg.appName||cfg.appId,data:collect(),updatedAt:firebase.firestore.FieldValue.serverTimestamp(),updatedAtMs:Date.now(),updatedByDevice:deviceId,schemaVersion:1};await ref().set(payload,{merge:true});original.setItem(metaKey,JSON.stringify({lastUpload:payload.updatedAtMs}));toast('Podatki so sinhronizirani')}catch(e){console.error(e);toast('Sinhronizacija ni uspela. Preveri povezavo in Firestore pravila.',true)}}
  function applyRemote(remote){if(!remote||!remote.data)return;applying=true;try{const current=collect();Object.keys(current).forEach(k=>{if(!(k in remote.data))original.removeItem(k)});Object.entries(remote.data).forEach(([k,v])=>original.setItem(k,v));original.setItem(metaKey,JSON.stringify({lastRemote:remote.updatedAtMs||Date.now()}))}finally{applying=false}toast('Prejeti so novejši podatki. Aplikacija se osvežuje.');setTimeout(()=>location.reload(),500)}
  async function startSync(user){currentUser=user;updateUI();const r=ref();const snap=await r.get();if(!snap.exists){if(hasLocal())await upload();else await r.set({appId:cfg.appId,appName:cfg.appName||cfg.appId,data:{},updatedAt:firebase.firestore.FieldValue.serverTimestamp(),updatedAtMs:Date.now(),updatedByDevice:deviceId,schemaVersion:1})}else{const remote=snap.data();const meta=JSON.parse(localStorage.getItem(metaKey)||'{}');if(!hasLocal())applyRemote(remote);else if(!meta.lastUpload&&!meta.lastRemote){await upload()}else if(remote.updatedByDevice!==deviceId&&(remote.updatedAtMs||0)>(meta.lastRemote||meta.lastUpload||0)){applyRemote(remote)}}
    unsubscribe=r.onSnapshot(s=>{if(!s.exists)return;const remote=s.data();const meta=JSON.parse(localStorage.getItem(metaKey)||'{}');if(remote.updatedByDevice!==deviceId&&(remote.updatedAtMs||0)>(meta.lastRemote||meta.lastUpload||0))applyRemote(remote)});
  }
  function stopSync(){currentUser=null;if(unsubscribe){unsubscribe();unsubscribe=null}updateUI()}
  function exportBackup(){const blob=new Blob([JSON.stringify({appId:cfg.appId,appName:cfg.appName,exportedAt:new Date().toISOString(),data:collect()},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=(cfg.appId||'aplikacija')+'-backup-'+new Date().toISOString().slice(0,10)+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);toast('Varnostna kopija je izvožena')}
  async function importBackup(e){const f=e.target.files&&e.target.files[0];if(!f)return;try{const obj=JSON.parse(await f.text());if(!obj.data||typeof obj.data!=='object')throw new Error('Neveljavna datoteka');if(obj.appId&&obj.appId!==cfg.appId&&!confirm('Kopija je iz druge aplikacije. Ali jo vseeno želiš uvoziti?'))return;applying=true;Object.keys(collect()).forEach(k=>original.removeItem(k));Object.entries(obj.data).forEach(([k,v])=>original.setItem(k,v));applying=false;if(currentUser)await upload();toast('Varnostna kopija je uvožena');setTimeout(()=>location.reload(),500)}catch(err){applying=false;toast('Uvoz ni uspel: '+err.message,true)}finally{e.target.value=''}}
  window.addEventListener('online',()=>{updateUI();if(currentUser)upload()});window.addEventListener('offline',updateUI);
  function boot(){injectUI();if(!window.firebase){toast('Firebase knjižnica se ni naložila.',true);return}try{firebase.firestore().enablePersistence({synchronizeTabs:true}).catch(()=>{});firebase.auth().onAuthStateChanged(u=>{if(u)startSync(u).catch(e=>{console.error(e);toast('Povezava z oblakom ni uspela.',true)});else stopSync()})}catch(e){console.error(e);toast('Firebase ni pravilno nastavljen.',true)}}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
